name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: FinBot-Crypto/.github/.github/workflows/deploy-service.yml@main
    with:
      service_name: fb-ml-training
    secrets: inherit
